---
- name: "(Handler: All OSs) Start NGINX"
  service:
    name: nginx
    state: started

- name: "(Handler: All OSs) Reload NGINX"
  service:
    name: nginx
    state: reloaded

- name: "(Handler: Debian/Ubuntu/CentOS/RedHat) Start NGINX Unit"
  service:
    name: unit
    state: started

- name: "(Handler: FreeBSD) Start NGINX Unit"
  service:
    name: unitd
    state: started
